### ISSUE TITLE
News

### ISSUE THREAD

**Issue by AiraComet** [MathHubInfo/Frontend#10]
Put the news on home and have a tab for the latest news and documented how it works in [the wiki](https://github.com/MathHubInfo/Documentation/wiki/administration#3-adding-a-news-post-needs-to-be-reworked).

**Comment by kohlhase** [comment]
And get the old news from the old web site and reinstate them.  There should also be a news feed (e.g. atom for this).

**Comment by kohlhase** [comment]
I guess Tom will look for a react framework for this.

**Comment by tkw1536** [comment]
Atom might be a little bit more difficult, because of the way react works (everything is done using client-side javascript).

**Comment by kohlhase** [comment]
actually RSS is just as good, I do not care

**Comment by kohlhase** [comment]
We decided that for now, we will have a jekyll-based static server for the news posts we have. I have rescued the old news at http://github.com/MathHubInfo/News. Tom will set this up and make the news available under http://mathhub.info/news by a redirect. 

We may later make a react.js based solution.

**Comment by kohlhase** [comment]
@tkw1536 this should only be a redirect away, but makes a large difference, could you just do that?

**Comment by tkw1536** [comment]
We have a very bare-bones implementation of this at https://beta.mathhub.info/news.
