### ISSUE TITLE
Replace MitM/smglom with MitM/core

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#111]
when on https://mathhub.info/library/group?id=MitM, I click on the "smglom", the system times out and gives me an empty screen. This is terrible for the OAF2 proposal.

**Comment by tkw1536** [comment]
Probably because MMT takes take too long. When is the deadline for this? I can have a more detailed look.

**Comment by Jazzpirate** [comment]
should be MitM/Core probably, by the way ;)

**Comment by kohlhase** [comment]
yes, now, ... but the issue was pre-rename.

**Comment by kohlhase** [comment]
We want to submit the proposal before the end of the month. So that is the deadline.

**Comment by tkw1536** [comment]
Works for me now https://mathhub.info/library/archive?lang=en&id=MitM%2Fsmglom

**Comment by tkw1536** [comment]
Probably the restart I had because of re-deployment cleared the cache and fixed it.

**Comment by Jazzpirate** [comment]
can you use MitM/core instead of MitM/smglom please? :)

**Comment by tkw1536** [comment]
Sorry, I missed that comment. Will do tomorrow.

**Comment by tkw1536** [comment]
Fixed. I have restarted the appropriate MMT instances and manually deleted the old `MitM/smglom` clones. Give it a few minutes, then `MitM/core` should have been cloned and appear on www and beta.

**Comment by kohlhase** [comment]
as of today, https://mathhub.info/library/group?lang=en&id=MitM also lists an `smglom` archive. That should go away.

**Comment by tkw1536** [comment]
That's likely because somewhere in the dependency tree. I did explicitly remove it.

**Comment by tkw1536** [comment]
Found it, its 'MitM/models'. Solving offline how to resolve this.

**Comment by tkw1536** [comment]
Fixed, removed `MitM/models` from MathHub after advice from @Jazzpirate. Then manually removed the `smglom` archive.
