### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by AiraComet** [MathHubInfo/Frontend#15]
Add the version to the footer.

**Comment by kohlhase** [comment]
Probably also a GIT revision of the various components, at least
* MMT version
* Front end 
And these should be linked to the repository at the rigth version.

**Comment by tkw1536** [comment]
* The semantic frontend version (from https://github.com/MathHubInfo/Frontend/blob/master/package.json#L3) is now exposed in the footer
* MMT does not know it's own git hash, however exposing the semantic version (release number) should be possible

**Comment by kohlhase** [comment]
> MMT does not know it's own git hash

I was thinking that the build process would (when it pulls) write the hash somewhere into a file and that MMT can read (and then knows). 

But I guess the release number should be sufficient.

**Comment by kohlhase** [comment]
This is almost finished. But (e.g. for the MathHub version) I see
```
 MathHub Version 0.0.2
(built 22:31:53 GMT+0200 (CEST))
```
this only shows the build time, not the build data, which is much more important.
