### ISSUE TITLE
need a way to in/exclude archives to/from MathHub

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#20]
I am looking at the new MathHub, and I am delighted with the library listings. 
BUT, I am seeing that there are quite a few archives that are either deprecated or too experimental to be shown in MathHub.info. 

In the old MathHub, we had an explicit configuration with a list of libraries and archives to be included. I do not think that this scales. Instead I guess we should have an entry in `META-INF/MANIFEST.MF` and `meta-inf/GROUP-MANIFEST.MF` that should regulate visibility and then (MMT can cache that for all I care).

As MathHub.info should be as inclusive as possible, I would propose a key `MathHub-hide` with various values that act as reasons why this archive is hidden in MathHub.info: 
* `MathHub-hide: deprecated` 
* `MathHub-hide: experimental`
So, if `MathHub-hide` is not given, the library or archive is listed, otherwise it could be listed in the front-end (e.g. in a list of deprecated libraries and archives). There may be other keys `MathHub-*` that regulate details of the listing.

**Comment by kohlhase** [comment]
Once this is implemented (or at least the key agreed upon), we should go through the archives and mark them appropriately.

**Comment by kohlhase** [comment]
Come to think of it, maybe a general `status` key would serve the bill here as well.

**Comment by tkw1536** [comment]
This is solved: Configuration is available in https://github.com/MathHubInfo/MathHub/blob/master/docker-compose.yml#L130.
