### ISSUE TITLE
Freeze Bug

### ISSUE THREAD

**Issue by AiraComet** [MathHubInfo/Frontend#33]
Fix the Freeze - Hash bug when building with the cache activated

**Comment by tkw1536** [comment]
This seems to be related to an upstream bug in webpack and HardWebpackSourcePlugin. I am going to disable it for now and keep the issue open until this is solved.

**Comment by tkw1536** [comment]
The reason for using HWSP is because we wanted to speed up webpack compilation. 
I managed to speed compilation (a clean development build takes ~11 seconds on my machine, a prod build ~ 22 seconds). 
Closing this issue as wontfix, as it is no longer needed.
