### ISSUE TITLE
"report an issue" functionality

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#39]
There are two functionalities I would like: 

* "report a MathHub issue" in the top-level "help": just open an issue via https://github.com/MathHubInfo/Frontend/issues/new

* "report a content issue": this should be part of the generated pages (e.g. under the library pages) or also in the glossary. Say we are in the english glossary entry "sets/bijective", then we should use the link https://gl.kwarc.info/smglom/sets/issue/new and prefill the title with "problem in bijective.en.tex". 

this would great for content curation.

**Comment by tkw1536** [comment]
@AiraComet the urls for this should not be hard-coded, instead they should be configurable in https://github.com/MathHubInfo/Frontend/blob/master/src/context/config.ts#L34.

**Comment by kohlhase** [comment]
The button for this could go next to the the new view source button.

**Comment by kohlhase** [comment]
@AiraComet It would be very good to have this functionality, and this seems easy to add to the front-end. 
In particular, the top-level "report an issue" functionality should be a five-minute fix and already helpful.

**Comment by AiraComet** [comment]
@kohlhase Except for the fact that every Report button links to https://github.com/MathHubInfo/Frontend/issues/new
is that how you imagined it?

**Comment by kohlhase** [comment]
I am not sure, the top-level menu entry is good. But it does not advertise that the issue to be reported is content-specific. 
I think I would like to have a green "issue" button near "Statistics". for the individual content-specific issues. And that button should have a hover text 
```
Report an issue with the contents of the current page on the archive issue tracker. 
```

**Comment by AiraComet** [comment]
I updated the button placement and added the hover text.
@tkw1536 added the content issue urls.
So @kohlhase  if you don't have any further comments this issue can be closed.

**Comment by kohlhase** [comment]
The new archive-level button is very nice.  
> So @kohlhase if you don't have any further comments this issue can be closed.

Actually, there is more I want (this is a different design which should be discussed). 
- the target url of the button should include `/new` so that we directly get into the new issue field. 
- We need the issue button at more levels (next is the file level, e.g. https://beta.mathhub.info/library/document?id=http%3A%2F%2Fgl.mathhub.info%2FMMT%2FLFX%2FRecords.omdoc&modules=http%3A%2F%2Fgl.mathhub.info%2FMMT%2FLFX%2FRecords%3FTypedRecords%2Chttp%3A%2F%2Fgl.mathhub.info%2FMMT%2FLFX%2FRecords%3FLFRecords&declarations=) 
- It would be great, if we could pre-load the issue with a pointer to the source file.

**Comment by kohlhase** [comment]
about the last point: There is an GitLab API for that:  https://docs.gitlab.com/ee/api/issues.html#new-issue (for gl.mathhub.info). So that is just a post request away. 

The pre-filling content is mentioned all the way on top here (second bullet point).

**Comment by kohlhase** [comment]
Also, I notice that https://beta.mathhub.info/library/group?id=MMT does not have a "report issue" button. But GitLab has group issues (here https://gl.mathhub.info/groups/MMT/-/issues) which can be used for that.

**Comment by tkw1536** [comment]
Issue buttons now exist
