### ISSUE TITLE
Deploy at the new MathHub at http://mathhub.info

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#44]
I think we are ready do deploy. When we do, we should have 
* a stable version on http://mathhub.info, which is manually updated (e.g. via a release branch)
* a development version on http://alpha.mathhub.info, which tracks the `devel` branch
I am not sure whether we also want a http://beta.mathhub.info version that tracks the `master` branch, but that could also be nice to have.

**Comment by tkw1536** [comment]
The new MathHub is currently deployed at https://mathhub.info. This currently runs the development versions of MMT and the Frontend. 

We should move this particular deployment to https://beta.mathhub.info and deploy a master-only version of MathHub to the TLD.

**Comment by kohlhase** [comment]
I fully agree. It seems that I inadvertently committed a local (test) change.

**Comment by tkw1536** [comment]
Both mathhub.info and beta.mathhub.info have been updated with respective versions.
