### ISSUE TITLE
beautify news

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#46]
We now have a first implementation as of #10, now we need to beautification.

**Comment by AiraComet** [comment]
Do we want to open a new page to show the content of the news or do we to show it directly in the card?

**Comment by AiraComet** [comment]
And if we want to open a new page:
Any design ideas to make the actual news more appealing?

**Comment by kohlhase** [comment]
* The News items we have tend to be quite short, so far.  
* So we can give a teaser (the first sentence) in the card. 
* I am not sure that the grid layout is ideal, since that does not show the timeline well. 
* We definitely need pagination, i.e. show the last 10 news items and then have a page with previous news.

**Comment by kohlhase** [comment]
Also take #73 #77 into account here.

**Comment by tkw1536** [comment]
The news page has gotten a couple of refreshes, I will close this.
