### ISSUE TITLE
Investigate missing description in MitM/Foundation

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#47]
I am looking at https://mathhub.info/#/library/archive/MitM%2FFoundation in beta. And I see two problems: 
* the slash between `MitM` and `Foundation` is percent-encoded (but should probably not be)
* it says "No description provided", but in `meta-inf/GROUP_MANIFEST.MF`, there is a description.

**Comment by kohlhase** [comment]
Ah, sorry, it was non-beta after all (see #48), I looked at the wrong system. So the first problem is already solved.

**Comment by tkw1536** [comment]
Fixed locally, deployment in a couple minutes
