### ISSUE TITLE
Native Changes Frontend

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#61]
#60 is mostly a mock-up for the "changes" functionalities. It has the problem that GitLab shows all libraries and archives on gl.kwarc.info, not just the ones that are on MathHub (a proper subset). 

Eventually we want to use the upcoming Inventory system to as a backend that supplies information about activity and changes, so that we can build a native interface that integrates well into MathHub. 

Especially, if we subset MathHub (see #24; e.g. to oaf.mathhub.info, see #25) we want the changed functionality to respect this subsetting. 

@AiraComet can already think about giving views for this, and then coordinate with @tkw1536 about the Inventory API.

**Comment by tkw1536** [comment]
Not sure if this is relevant still, closing.
