### ISSUE TITLE
localized issues

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#66]
Just like we have localized discussions (JOBAD links to forum-style posts) we should have localized issues (JOBAD links to GitLab Issues @tkw1536 should help). A localized issue should have a bug icon in the side bar (or a gitlab facivon) and upon establishing it should (via the GitLab API @RochauD should help) create a GitLab issue. @m-iancu should coordinate development.

**Comment by tkw1536** [comment]
This is implemented by "Report an Issue" links and can be closed.
