### ISSUE TITLE
add tags to news

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#73]
Issue at https://oaf.mathhub.info/node
It would be great, if we could specialize news to the respective subdomains of mathhub, e.g. http://oaf.mathhub.info. For that we would have to 
- have a classification system for thew news items, e.g. keywords like `oaf`, `smglom`, `mathhub`. The latter lets the news be present on all subdomains. 
- have a more clever news presenting system.

**Comment by tkw1536** [comment]
This should be solvable in principle by adding tags to news and then having a route that only displays news with a limited set of tags.

**Comment by kohlhase** [comment]
OK, then I will start tagging away.

**Comment by kohlhase** [comment]
I have added the following tags: OAF, Sys, MitM, ODK, Libs, MMT
So you have content.

**Comment by tkw1536** [comment]
I'm not sure this makes too much sense. We can display tags, but I don't believe there is enough news items to warrant actually implement filtering by tags. 
We should also consider that we might be duplicating functionality with the kwarc.info homepage.

**Comment by kohlhase** [comment]
Let's close this until we have more news.
