### ISSUE TITLE
integrate KAT into MathHub

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#87]
It would be great if we could use KAT for casually producing OMDoc markup. For that KAT needs to be integrated into MathHub first. 
This is the MathHub-side tracker bug, to be used for planning, the KAT-side one is https://github.com/KWARC/KAT/issues/47 cc: @tkw1536  @LiftnLearn
Here are the things that should be done MathHub-side (most of the steps need to be elaborated considerably). 
- accept HTML5 as a surface language (see #99)
- add the KAT JS into the served pages. 
- store the RDF annotations from KAT
- make an interaction to harvest the RDF and create OMDoc from it and store the OMDoc.

**Comment by tkw1536** [comment]
This will likely require a lot of work, since the old-style javascript from KAT depends on the old JOBAD and will not simply be integratable in the new MathHub,

**Comment by kohlhase** [comment]
closing.
