### ISSUE TITLE
news on beta.mathhub.info via a devel branch on the News repos?

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#89]
I think it would be good to have a `devel` branch on the [MathHub News repos](https://github.com/MathHubInfo/News), which would be used for news on http://beta.mathhub.info Then we could stage the news (new featurs mostly) and would be merge into `master` when mathhub.info is updated. 

This should be relatively easy to config and an effective means of communication.

**Comment by tkw1536** [comment]
Fixed and deployed on beta.mathhub.info.
