### ISSUE TITLE
certificate problem for beta?

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#90]
I am getting 

Your connection is not secure

The owner of beta.mathhub.info has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

Learn more…

Report errors like this to help Mozilla identify and block malicious sites

**Comment by tkw1536** [comment]
This is a temporary issue, that occurs from time to time. 

Also, please don't make issues every time the beta goes down. It is called beta for a reason.
