### ISSUE TITLE
no content even if there is. 

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#96]
https://beta.mathhub.info/library/archive?id=HelloWorld%2FMMT&modules=&dedclarations= says "no content", but there are two MMT files in the archive. What happens?

**Comment by kohlhase** [comment]
I have a suspicion: the HelloWorld examples are not built. What do I have to do do build them. There should be a auto-build feature in MathHub.

**Comment by tkw1536** [comment]
Yes that's exactly what is happening. Previously, those pages would show a 404 error, the MMT backend now just returns a pseudo-response with the empty text.

**Comment by kohlhase** [comment]
Oh, and opening the /MathHub/HelloWorld/MMT/{fol,pl}.mmt into IntelliJ gives me errors I am not sure I understand. 
@tkw1536 could you have a look?

**Comment by tkw1536** [comment]
Content problems are something @Jazzpirate should look at.

**Comment by tkw1536** [comment]
no longer the case
