### ISSUE TITLE
archive descriptions missing. 

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#97]
https://beta.mathhub.info/library/archive?id=HelloWorld%2FMMT&modules=&dedclarations=
says "no description provided" even though https://gl.mathhub.info/HelloWorld/MMT/blob/master/META-INF/MANIFEST.MF contains 
```
description:desc.html
```
and [desc.html](https://gl.mathhub.info/HelloWorld/MMT/blob/master/META-INF/desc.html) exists. 

This should be easy to fix (backend problem?)

**Comment by tkw1536** [comment]
Description paths are resolved relative to the archive root folder, not the manifest folder. 
I will fix this in the next MMT release, but until then simply move desc.html to the root folder.

**Comment by kohlhase** [comment]
I do not really want to move the desc.html files, I think they are where they morally belong (as meta-information). I would rather just wait.
Another fix would be to just change 
```
description:desc.html 
```
to 
```
description: META-INF/desc.html 
```
everywhere. That would also work without a change to MMT.  


> Description paths are resolved relative to the archive root folder, not the manifest folder.

is this the case for all other paths as well?

**Comment by tkw1536** [comment]
I do not think we should change paths, MMT/MathHub should be smart enough to figure out where the `desc.html` files are (I have a fix implemented, testing that right now). 

Not sure what you mean by other paths, the only ones I am aware of is `group/meta-inf` manifest paths. 
There is no central path resolving, however those are also resolved relative to the (git) repository they are in. Notably the group case, the git root happens to be the location of the manifest file.

**Comment by kohlhase** [comment]
Then this should (soon work on beta), correct? That is enough for me.

**Comment by kohlhase** [comment]
Ah, it already does.
