### ISSUE TITLE
design for i18n and high-level reformulation

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/Frontend#99]
It would be good if we could (at some point) internationalize the MathHub user interface. There are standard ways of doing this; One level of indirection, taking all actual texts from a JSON-based dictionary.
That would also allow people like me  to change the words/snippets on the interface without having to understand the code. See also #98 
cc: @katjabercic

**Comment by tkw1536** [comment]
We should also look at existing i18n libraries for React before we start designing our own implementation

**Comment by kohlhase** [comment]
I think this is done correct?

**Comment by tkw1536** [comment]
Yes, this is done (sorry for taking about 18 months to respond).
